### ISSUE TITLE
Reparto de trabajo para la entrega del 23-abril

### ISSUE THREAD

**Issue by dpriver** [UCM-SistemasWeb-Veery/Veery#1]
Reparto de trabajo para la entrega del 23-abril

**Comment by albertomg994** [comment]
Si, ahora copio la issue.

**Comment by amiedes** [comment]
## 1. OTROS 

index.html - Muestra también las noticias (Rafa)
login.html -  (Rafa)

registro.html (df_register_user.jpg) (Nacho)
busqueda.html (df_search_results.jpg) (Nacho)

## 2. VISUALIZACIÓN DE CONTENIDOS (Denys Ruso)

album_view.html (df_album_view.jpg)
artist_view.html (df_todo_artista.jpg)
genero_view.html (df_resultados_pinchar_en_un_genero.jpg)

## 3. NAVEGACIÓN (Rafa todo)

header.html
footer.html
sidebar_left.php
sidebar_right.php

## 4. REPRODUCCIÓN (Alberto y Denys)

play_music.html (sólo 1er plano de momento)
play_video.html
play_live.html

## 5. USUARIO REGISTRADO (Denis Pinto)

usr_registrado_main.html
usr_modificar_info.html 
usr_baja.html

## 6. ARTISTA

artista_main.html (Javier)
art_modificar_info.html (Javier)
art_baja.html (Javier)
upload_main.html (Javier)
    upload_song.html (Alberto)
    upload_video.html (Alberto)
    empezar_ensayo.html (Alberto)
    empezar_concierto.html (Alberto)

## 7. ADMINISTRADOR (Nacho)

admin_main.html
lista_usuarios.html (df_all_users_list.jpg)

**Comment by densypko** [comment]
Tener cuidado subir solo las imganes .png o .jpg.

**Comment by denmadrid91** [comment]
Alberto,el punto 4 que quiere decir con reproducción ?
