### ISSUE TITLE
La pag se ve fatal...

### ISSUE THREAD

**Issue by dpriver** [UCM-SistemasWeb-Veery/Veery#11]
Acabo de descargarme master y se me ve fatal la página, no hay enlaces de nada y está todo descolocado...

**Comment by javber** [comment]
Yo lo veo todo bien, y tengo el master actualizado.

**Comment by iamraffe** [comment]
Tienen que tener cuidado con lo que yo estoy desarrollando. Ver que mis
cambios son compatibles con lo que tienen en los php independientes, porque
voy haciendo refactoring en cada commit.
On Apr 17, 2015 10:40 PM, "javito003" notifications@github.com wrote:

Yo lo veo todo bien, y tengo el master actualizado.

**Comment by dpriver** [comment]
Pues esto veo yo...

![captura de pantalla de 2015-04-17 22 56 29](https://cloud.githubusercontent.com/assets/4693570/7210786/1e15e43a-e555-11e4-9453-4f82648e9b94.png)

Antes se veían todas las imágenes descolocadas... sería por las clases de css. Es así como debe verse?
