### ISSUE TITLE
Pulls a master

### ISSUE THREAD

**Issue by dpriver** [UCM-SistemasWeb-Veery/Veery#2]
Para ir cogiendo disciplina, si alguien hace pull a master directamente, avisaré para que no se pierda trabajo y haré reset.

No hace falta hacer un un request a cada commit pequeño, solo para cambios significativos.

**Comment by amiedes** [comment]
No te entiendo. El segundo párrafo te refieres a los commits pequeños a master? ¿Qué hace el reset exactamente? Y otra cosa: cuando hablas de "commits inútiles" (no aquí, sino por el whatsapp) a que te refieres?

**Comment by dpriver** [comment]
Reset es volver a un commit anterior, es decir, descartar commits.
Me refiero a que hacer commit no es sinónimo de guardar, piensa que eso va dejando un registro, pero sobre todo me refiero a la hora de hacer pull request. Cada vez que se hace un merge en master, todo el mundo tiene que ver si es necesario acualizar su versión para evitar problemas, asique lo ideal es hacer pull a master cuando ya se tenga alguna parte interesante funcionando.

Commits inútiles son los que no aportan nada y ensucian el registro, por ejemplo, eso que había de un commit subiendo los htmls, otro para borrarlos, otro para crearlos de nuevo... esas cosas hay que evitarlas.

**Comment by amiedes** [comment]
Vale, entendido!! Entonces lo que hay que hacer con los pequeños cambios es ir guardándolos en tu equipo y sólo cuando tengas los suficientes hacer el commit?
Otra pregunta: si hago varios cambios en mi equipo pero no hago el commit y después cambio de rama en mi equipo para hacer algo (lo que sea), pierdo estos cambios al no haber hecho el commit?

**Comment by dpriver** [comment]
No necesariamente, Si te interesa un uso más avanzado de git, busca sobre la **staging zone**, 
tampoco quería liarme a explicar esas complicaciones, pero la documentación de git es bastante buena, asique dejo en enlace.
http://git-scm.com/book/en/v2/Getting-Started-Git-Basics

**Comment by dpriver** [comment]
Bueno, como veo que al final todo el mundo pasa de request... cierro esto.
