### ISSUE TITLE
Cancelar cuenta

### ISSUE THREAD

**Issue by javber** [UCM-SistemasWeb-Veery/Veery#21]
Art baja,usr baja, son en sí, las mismas páginas. He echo un cancelar_cuenta.pho genérico, lo sustituimos por todos los *_baja?

**Comment by javber** [comment]
También para las páginas de modificar

**Comment by amiedes** [comment]
Yo votaría por que no, pues es posible que en un futuro su comportamiento se acabe diferenciando más.

**Comment by javber** [comment]
Vale si,me has convencido jaja
