### ISSUE TITLE
Enlazado de todos los archivos

### ISSUE THREAD

**Issue by amiedes** [UCM-SistemasWeb-Veery/Veery#23]
Estaba pensando que una forma de hacer accesibles los php relacionados con la vista de usuario registrado y de artista podría ser aprovechando el news feed de la pantalla principal. Dónde aparece el nombre de usuario (@loquesea) podríamos reservar 2 o 3 que enlazasen a artist_view.php y otros tantos a user_view.php o como se llame.
Esto primero para la vista de un perfil ajeno, para la vista del perfil propio podría hacerse un desplegable cutre en "My Veery" que de a elegir si ver tu perfil como usuario o tu perfil como artista (artist_main.php y user_main.php)

**Comment by iamraffe** [comment]
Si claro, hay unos que tiran para usuarios y otros pa artista.

2015-04-22 17:39 GMT+02:00 Alberto Miedes Garcés notifications@github.com:

**Comment by iamraffe** [comment]
Es que estaba esperando a ver que paginas teniamos a ver como hacia para
enlazarlo todo desde el home. Porque no tenemos un home de musica, video ni
directo. Asi que hay que darle la vuelta.

2015-04-22 17:50 GMT+02:00 Rafael Ramirez raffe90@gmail.com:
