### ISSUE TITLE
Entrega final

### ISSUE THREAD

**Issue by amiedes** [UCM-SistemasWeb-Veery/Veery#28]
Varios puntos:
1. Respecto al estado del respositorio, yo soy partidario de copiar y pegar directamente en master todo lo del branch CSS, y de hacerlo lo antes posible antes de que nos pongamos a trabajar este fin de semana. Son 5 minutos y soy partidario de hacerlo ya. Que lo haga quien quiera o si quereis lo hago yo, pero necesito vuestro consentimiento.
2. Dejar de discutir temas sobre implementación en el grupo de Whatsapp. Si segúis haciéndolo o me acabaré saliendo o empezaré a ignorar sistemáticamente todos los mensajes no leidos, que puede desembocar en una falta de coordinación tremenda. Personalmente pienso que esto nos beneficia a todos.
3. Si nadie tiene inconveniente, esta tarde me pondré a trabajar sobre la página de búsqueda de contenidos, encargada de recuperar todo el listado de canciones, videos, etc. de la BD. Pero no lo subiré a github hasta que no esté el repositorio listo en master.
4. Respecto a la base de datos: ¿Qué os parece abrir un branch de máster sólo para ir colgando nuestras respectivas versiones de la BD, de forma que podamos descargarla e importarla en nuestro phpmyadmin en local para trabajar? Este branch nunca haría un merge con el master, sería sólo para ir elaborando lo que son las tablas y los datos de ejemplo de la BD, y que podamos volver a descargárnosla e importarla en cualquier momento.

**Comment by javber** [comment]
Me parece bien todo. Pero el branch mas actualizado ahora es el
branch_javier no el css.

**Comment by iamraffe** [comment]
1. Me da igual, puedes copiarlo.
2. Ok.
3. Aquí no entiendo a que te refieres. Que entiendes por página de búsqueda? Lo que describes es una funcion que llamas desde cualquier lugar de la app.
4. Por que hay versiones diferentes de la BD? En tal caso tomarnos una hora y hacer migrations como es debido. 

Y propongo un quinto. Cual es el reparto del trabajo para esta entrega?

**Comment by amiedes** [comment]
1. @javito003  ¿Entonces cojo tu rama y la copio tal cual en master, no?
2. Por página de búsqueda me refería a  esta: http://fundaseth.es/proyectos/veery/busqueda.php Hacer el código necesario para que al pulsar el botón de buscar en está página se muestre el contenido de la BD en esta página.
3. De momento sólo hay una, la que ha hecho javier (o eso creo). Pero me imagino que a medida que vayamos trabajando y hasta que tengamos la versión definitiva de la BD es posible que algunas personas quieran añadir una tabla nueva o algún campo adicional. Tampoco tengo muy claro cual es el procedimiento habitual para esto, así que es cuestión de hablarlo. ¿Qué es lo de las 'migrations'?
4. El reparto de trabajo yo pensaba que íbamos a hablaro en alguna reunión la semana que viene, pero como habéis empezado a hacer cosas pues me imagino que si tenemos algo en mente podemos ir haciéndolo.

**Comment by javber** [comment]
Sii coge mi rama y ponla directamente al master.
La base de datos esta en la carpeta sql/bd.sql. Cada vez que hay tablas
nuevas o datos,hay que añadirlo a ese archivo(phpmiadmin lo hace cuando lo
exportas).
La proxima semana repartimos el trabajo bien.Pero este finde tenemos que
hacer cosas que nos quedamos atrasados (cada uno se asigne lo que pueda)

**Comment by iamraffe** [comment]
No estoy de acuerdo con vosotros chicos. En mi experiencia ir a ciegas nos hará perder el doble de tiempo (haciendo y corrigiendo). 

Recomendaría que en vez de tocar código, investigasen primero el como.

**Comment by amiedes** [comment]
Bueno, pues voy probar a hacer lo de búsqueda sólo en local aunque sea sólo por ir familiarizándome un poco mas con php y las BD.
El master lo actualizo después de comer, ya os aviso cuando lo haya hecho.

**Comment by iamraffe** [comment]
La busqueda al final va a ser codigo ajax que llamas y le pasas los parametros. Eso ya lo tengo implementado, pero a nivel global ademas. Es decir, en esa pagina de busqueda, buscas cualquier campo. Pero despues cuando quieres mostrar el perfil de un artista, tambien buscas. Me explico? Es decir es una misma funcion que se adapta a los parametros que recibe.

Como te digo, eso ya lo tengo implementado de buena forma. Podria subirlo esta tarde al conectarme a la compu. 

(He ido adelantando cosas que sabia que necesitariamos en el proyecto y que a lo mejor no seria facil de entender en un par de semanas para vosotros. Como este tio pone las entregas asumiendo que lo que ha dado en clase esta mas que entendido me parecia adecuado)

**Comment by amiedes** [comment]
1. Vale, ya está todo en master. Cuando nos aseguremos de que está todo correcto borramos las ramas que se han quedado coleando para que no nos confundamos.
2. Vale, en ese caso dejo lo de la búsqueda en paz. ¿Puedo entonces encargarme de ir elaborando el php que procesa los formularios de los archivos que implementé yo para la primera entrega? (upload_song.php y upload_video.php)

**Comment by javber** [comment]
Mañana podeis quedaros para hacer una reunión para hablar y asignar trabajo?
Nos quedan tres semanas para la página web,pero la última semana tenemos
examen de amplicación de redes y la presentación de aso,que no es muy
complicado pero es tiempo que hay ponerse con ello.
Por este motivo,podriamos casi terminar la página web para la semana
anterior a la entrega,es decir,meternos el atracón esta semana y la
siguiente,¿que os parece?

**Comment by densypko** [comment]
Yo si.

Enviado desde Correo de Windows

De: javito003
Enviado el: ‎lunes‎, ‎11‎ de ‎mayo‎ de ‎2015 ‎15‎:‎33
Para: UCM-SistemasWeb-Veery/Veery

Mañana podeis quedaros para hacer una reunión para hablar y asignar trabajo?
Nos quedan tres semanas para la página web,pero la última semana tenemos
examen de amplicación de redes y la presentación de aso,que no es muy
complicado pero es tiempo que hay ponerse con ello.
Por este motivo,podriamos casi terminar la página web para la semana
anterior a la entrega,es decir,meternos el atracón esta semana y la
siguiente,¿que os parece?

**Comment by iamraffe** [comment]
Por mi bien. Yo salgo a las 12 de EC

2015-05-11 15:34 GMT+02:00 Denys Sypko notifications@github.com:

**Comment by densypko** [comment]
Yo salgo a las 14.00, tengo práctica de SER. Pero podéis empezar y si lo acabáis hacer un resumen por aquí.

Enviado desde Correo de Windows

De: raffe
Enviado el: ‎lunes‎, ‎11‎ de ‎mayo‎ de ‎2015 ‎15‎:‎38
Para: UCM-SistemasWeb-Veery/Veery
CC: Denys Sypko

Por mi bien. Yo salgo a las 12 de EC

2015-05-11 15:34 GMT+02:00 Denys Sypko notifications@github.com:

**Comment by javber** [comment]
A ver,podemos tener la reunion a las dos,como os va esa hora?

**Comment by iamraffe** [comment]
Yo a esa hora no puedo, pero digo lo mismo que Denys, podeis reunirse sin
mi y me cuentan que me toca.

2015-05-11 16:08 GMT+02:00 javito003 notifications@github.com:

> A ver,podemos tener la reunion a las dos,como os va esa hora?
>

**Comment by javber** [comment]
Seria importante que tu estubieras Rafa,eres el que mas sabes y el que
mejor podrias guiarnos jaja

**Comment by densypko** [comment]
Pues la única opción es quedarse a las 12.00. Entonces.

**Comment by javber** [comment]
Si alberto tampoco se queda,que otro dia podeis?

**Comment by javber** [comment]
Entonces a ver,por ahora a las doce somos rafa y yo. Dennis y nacho
podeis?aunque sea media hora

**Comment by nachoferre** [comment]
Yo a las 12 puedo estar un rato
