### ISSUE TITLE
Vista de álbum y la mayoría de las imágenes dan 404

### ISSUE THREAD

**Issue by amiedes** [UCM-SistemasWeb-Veery/Veery#32]

**Comment by iamraffe** [comment]
Los issues no funcionan así, no abras un issue extra sobre uno que ya
existe.

**Comment by dpriver** [comment]
De hecho:
1. Si vas desde HOME o EDITAR a cualquiera de las pestañar de la barra izq, dan 404.
2. Si vas desde ADD POST te lleva a una página en blanco.
3. SI vas desde MY VEERY, te lleva a una página de usuario vacía.

**Comment by iamraffe** [comment]
No entiendo como están llegando a esas vistas. 

La de música y descubre normal, aun no está, pero lo otro?

Y que imagenes son las que no veis?

**Comment by amiedes** [comment]
![img_2015-06-23 18 38 10](https://cloud.githubusercontent.com/assets/9287468/8311535/13b47310-19d7-11e5-9aab-502ae7ed8355.jpg)
Aquí se llega logueándome y después buscando a jayz en el cuadro de búsqueda.

**Comment by iamraffe** [comment]
Vale, es que JayZ no se supone que exista.

2015-06-23 18:39 GMT+02:00 Alberto Miedes Garcés notifications@github.com:

**Comment by amiedes** [comment]
@iamraffe Alguna razón en particular por la que no puedo cerrarla? O es de coña?

**Comment by iamraffe** [comment]
@amiedes me aburría jaja

**Comment by amiedes** [comment]
Ok 🤣 ! Es que como las creé yo y están abierta me salen en el listado global de issues y se me mezclan con las del trabajo 😞
