### ISSUE TITLE
Duda páginas upload

### ISSUE THREAD

**Issue by javber** [UCM-SistemasWeb-Veery/Veery#4]
¿Qué diferencia hay entre upload_main,upload_video y upload_song?¿No se podría juntar todo?¿Para hacer tres páginas que sean iguales y que la diferencia sea el título de vido o canción.
Y si quereis dejarlo así, ¿Qué tendría upload_main?No entiendo su objetivo si ya estan los otros dos uploads

**Comment by amiedes** [comment]
La imagen de los bocetos es la misma, pero en la realidad no será así. Una vez que pinchas en upload video, song o lo que sea te lleve a otra página más específica.

**Comment by javber** [comment]
Yo voto por eliminar upload_main. He estado haciendo la página de modificar el perfil de un artista,y directamente si quiere subir un vídeo o una canción, va a la pagina de upload_video o upload_song.

**Comment by amiedes** [comment]
Es planteable, podrían ponerse directamente los 4 botones en la página principal del artista (pero que los vea él solo). ¿Qué opináis?
