### ISSUE TITLE
Fecha límite

### ISSUE THREAD

**Issue by javber** [UCM-SistemasWeb-Veery/Veery#6]
¿Os parece que nos pongamos como máximo el domingo por la noche para tener cada uno sus htmls? Lo digo porque luego habra que juntar todo y hacer las css de botones y cosas así, y nos puede tirar unos días.

**Comment by amiedes** [comment]
Si, yo creo que es lo que hay que hacer.

**Comment by dpriver** [comment]
Yo también lo creo, pero desgraciadamente me va a ser muy dificil poder tenerlo para entonces...
