### ISSUE TITLE
Botones de vuelta atras

### ISSUE THREAD

**Issue by javber** [UCM-SistemasWeb-Veery/Veery#7]
¿El botón de vuelta atrás donde va a estar, en cada html que hagamos nosotros, o en el marco principal(header,sliders)?

**Comment by densypko** [comment]
Como que de ¿atrás? el botón de escape va ser el logo creo.

**Comment by javber** [comment]
El típico botón que te vuelve a tus páginas anteriores dentro de una aplicación. La pregunta es que donde va a estar situado ese botón.

**Comment by densypko** [comment]
En ninguna de las aplicación de nuestro estilo he visto un botón que te vuelve a tus paginas anteriores tienes barras derecha izquierda cabecera "no lo se".
