### ISSUE TITLE
Estructura

### ISSUE THREAD

**Issue by javber** [UCM-SistemasWeb-Veery/Veery#8]
Las páginas php que estamos haciendo tienen que tener todas la estructura con el header,footer,sliders? o van a ser añadir a una estructura principal?

**Comment by amiedes** [comment]
Se pone con el import

**Comment by javber** [comment]
He estado viendo, que por ejemplo Dennys, en sus php pone los includes de header,footer.

**Comment by densypko** [comment]
Pero si no como lo juntas.

**Comment by densypko** [comment]
La idea erá hacerlo así, para no repetir el código y trabajar por separado.

**Comment by javber** [comment]
Entonces incluyo la estructura de header..en mis php?

**Comment by densypko** [comment]
Si te refieres a los includes si , si no como se va a ver.

**Comment by javber** [comment]
Por eso preguntaba, no sabia si había otra forma que directamente solo se metía el contenido.
Gracias.
