### ISSUE TITLE
Css de elementos muy concretos

### ISSUE THREAD

**Issue by dpriver** [UCM-SistemasWeb-Veery/Veery#9]
No me queda muy claro como estamos planteando las css, cada uno define las clases que necesite si son muy concretas? por ejemplo, necesito un estilo para el título y la descripción de los tracklist... pero para los botones deberíamos usar todos la misma, no?
O en vez de definir clases definimos ids para cada uno?

**Comment by denmadrid91** [comment]
Lo mejor seria hacer las css y añadir las al final de  custom.css. Poniendo los comentarios  ,porque a lo mejor los demás lo puede reutilizar. Pero actualizar lo más antes posible o tener siempre la versión actualizada del máster para no tener conflictos.
